apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: express
        image: sunseo18/opensource_node:latest
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: node-mysql
              key: db_host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: node-mysql
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: node-mysql
              key: db_password
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: node-mysql
              key: db_database
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-svc
spec:
  selector:
    app: node
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-ingress
spec:
  rules:
  - host: opensource.sample.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: node-svc
            port:
              number: 80
